//  PRODUCTOS CELULARES, HABR´´A UNA TABLA PRODUCTOS, OTRA ESPECIFICACIONES CON EL PRODUCTO_ID PODRE VER MAS DETALLES.
// TABLA DE INVENTARIO DONDE REGISTRARÉ ENTRADAS Y SALIDAS DE PRODUCTOS CON SU PRODUCTO_ID.
// ADEMAS UNA TABLA STOCK DONDE TENDRE CADA PRODUCTO_ID Y LA CANTIDAD ACTUALIZADA DE STOCK QUE POSEE.


